name: Dependency Review

on:
  pull_request:

permissions:
  contents: write
  statuses: write

jobs:
  dependency_review:
    name: Dependency review
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          java-package: jdk
          distribution: microsoft
        
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v2.0.1

      - name: Dependency validation
        id: dependency_validation
        uses: actions/dependency-review-action@v3
        continue-on-error: true
        with:
          fail-on-scopes: "runtime, development, unknown"

      - name: Publish status to PR
        uses: octodemo/github-status-action@v2
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: ${{ steps.dependency_validation.outcome }}
          context: Dependency scanning results / Dependency Review
          description: "${{ steps.dependency_validation.outcome }} (see details for more information)"
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
